### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key:DSi0hB045eca03173200b306I3xzrcdd

origin=64999&destination=64942&weight=1000&courier=jne